baseURL = "https://tobilehman.com/"
languageCode = "en-us"
title = "Tobi Lehman"
theme = "hugo-code"
paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Tobi Lehman"
    info = "Programming, mathematics and optimism"
    description = "Tobi Lehman"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/tlehman/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/tobi_lehman/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/tobilehman/"

[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase fa-2x"
    weight = 3
    url = "https://keybase.io/tlehman"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"
